### ISSUE TITLE
Works fine, just got a console info:

### ISSUE THREAD

**Issue by j2l** [zlatnaspirala/compositor#1]
Hey, thanks for sharing this project.
Here's what I got in the Node console:
`record-canvas doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.`
but it works so, it's fine to me.

**Comment by zlatnaspirala** [comment]
@j2l  Do `git pull` i make little changes.
Please tellme did you use git project or `npm i record-canvas` ?

If you use npm service then use : 

Javascript ->
```js
import RC from "record-canvas";
let options = {
  // ref to the canvas dom element
  injectCanvas: document.getElementsByTagName("canvas")[0],
  frameRequestRate: 30,
  videoDuration: 10,
  outputFilename: "record-canvas.mp4",
  mineType: "video/mp4",
  resolutions: '800x600'
}
this.recordCanvas = new RC.RecordCanvas(this.options);
```
Typescript ->
```ts
import RC from "record-canvas";
let options = {
  // injectCanvas: "orId",
  injectCanvas: document.getElementsByTagName("canvas")[0],
  frameRequestRate: 30,
  videoDuration: 10,
  outputFilename: "record-canvas.mp4",
  mineType: "video/mp4",
  resolutions: '800x600'
}
this.recordCanvas = new (RC as any).RecordCanvas(this.options);
```

**Comment by j2l** [comment]
Thank you @zlatnaspirala 
I `npm i record-canvas`
I'll try your code ASAP this week
